name: Build Cheeky Release

# This workflow builds everything automatically with ZERO local setup required
# Just push a tag and GitHub Actions does the rest!

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0-dev'

jobs:
  build-images:
    name: Build ${{ matrix.arch }} Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: armv8
            models: "Pi Zero 2 W, Pi 3, Pi 4, Pi 5"
            output_name: cheeky-armv8

          - arch: armv7
            models: "Pi 2"
            output_name: cheeky-armv7

          - arch: armv6
            models: "Pi Zero W, Pi 1"
            output_name: cheeky-armv6

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y xz-utils

      - name: Create test image (CI/CD placeholder)
        run: |
          mkdir -p build-output
          # For CI/CD, create a small test image (~10MB)
          # In production, replace with actual DietPi image download
          dd if=/dev/zero of=build-output/cheeky-${{ matrix.arch }}-${{ github.ref_name }}.img bs=1M count=10
          echo "Created test image for ${{ matrix.arch }}"
      
      - name: Set version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi
      
      - name: Compress image
        run: |
          cd build-output
          xz -9 -v cheeky-${{ matrix.arch }}-${{ steps.version.outputs.VERSION }}.img

      - name: Generate checksums
        run: |
          cd build-output
          sha256sum cheeky-${{ matrix.arch }}-*.img.xz > cheeky-${{ matrix.arch }}-${{ steps.version.outputs.VERSION }}.img.xz.sha256
          md5sum cheeky-${{ matrix.arch }}-*.img.xz > cheeky-${{ matrix.arch }}-${{ steps.version.outputs.VERSION }}.img.xz.md5

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cheeky-${{ matrix.arch }}-${{ steps.version.outputs.VERSION }}
          path: |
            build-output/cheeky-${{ matrix.arch }}-*.img.xz
            build-output/cheeky-${{ matrix.arch }}-*.sha256
            build-output/cheeky-${{ matrix.arch }}-*.md5

  build-qemu:
    name: Build QEMU Bundles
    runs-on: ubuntu-latest
    needs: build-images
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi
      
      - name: Download QEMU kernel
        run: |
          mkdir -p qemu-build
          wget -q https://github.com/dhruvvyas90/qemu-rpi-kernel/raw/master/kernel-qemu-5.10.63-bullseye -O qemu-build/kernel-qemu
          wget -q https://github.com/dhruvvyas90/qemu-rpi-kernel/raw/master/versatile-pb.dtb -O qemu-build/versatile-pb.dtb
      
      - name: Create bundles
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          REPO="${{ github.repository }}"
          cd qemu-build

          # Copy directories from repo
          cp -r ../qemu/linux . && cp -r ../qemu/macos . && cp -r ../qemu/windows .

          # Rename templates to remove .template extension
          for dir in linux macos windows; do
            if [ -f "$dir/start-qemu.sh.template" ]; then
              mv "$dir/start-qemu.sh.template" "$dir/start-qemu.sh"
            fi
            if [ -f "$dir/start-qemu.bat.template" ]; then
              mv "$dir/start-qemu.bat.template" "$dir/start-qemu.bat"
            fi
          done

          # Replace placeholders in scripts
          for file in linux/start-qemu.sh macos/start-qemu.sh windows/start-qemu.bat windows/README.txt linux/README.md macos/README.md; do
            if [ -f "$file" ]; then
              sed -i "s|VERSION_PLACEHOLDER|$VERSION|g" "$file" 2>/dev/null || sed -i '' "s|VERSION_PLACEHOLDER|$VERSION|g" "$file"
              sed -i "s|REPO_PLACEHOLDER|$REPO|g" "$file" 2>/dev/null || sed -i '' "s|REPO_PLACEHOLDER|$REPO|g" "$file"
            fi
          done

          # Copy kernel/dtb to each bundle
          for dir in linux macos windows; do
            cp kernel-qemu "$dir/"
            cp versatile-pb.dtb "$dir/"
          done

          # Package
          tar czf cheeky-qemu-linux-${VERSION}.tar.gz -C linux .
          tar czf cheeky-qemu-macos-${VERSION}.tar.gz -C macos .
          cd windows && zip -r ../cheeky-qemu-windows-${VERSION}.zip . && cd ..
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: qemu-bundles
          path: qemu-build/*.{tar.gz,zip}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-images, build-qemu]
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: List artifacts
        run: find . -type f \( -name "*.img.xz" -o -name "*.tar.gz" -o -name "*.zip" -o -name "*.sha256" -o -name "*.md5" \) | sort

      - name: Delete old release if exists
        run: |
          gh release delete ${{ github.ref_name }} -y 2>/dev/null || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Cheeky ${{ github.ref_name }}
          body: |
            ## 🍑 Cheeky ${{ github.ref_name }}

            **Download, flash, boot - that's it!**

            ### 📥 For Physical Raspberry Pi

            | Pi Model | Download |
            |----------|----------|
            | Pi Zero 2 W, Pi 3, Pi 4, Pi 5 | cheeky-armv8-*.img.xz |
            | Pi 2 | cheeky-armv7-*.img.xz |
            | Pi Zero W, Pi 1 | cheeky-armv6-*.img.xz |

            ### 🖥️ Test in QEMU (No Pi Needed)

            | Platform | Download |
            |----------|----------|
            | Linux | cheeky-qemu-linux-*.tar.gz |
            | macOS | cheeky-qemu-macos-*.tar.gz |
            | Windows | cheeky-qemu-windows-*.zip |

            ### 📡 Headless WiFi Setup

            Before first boot, edit `dietpi-wifi.txt` on boot partition:
            ```
            aWIFI_SSID[0]='YourNetwork'
            aWIFI_KEY[0]='YourPassword'
            ```

            Full docs: [WiFi Setup Guide](docs/WIFI-SETUP.md)

            ---

            🍑 Made with cheekiness by the community
          files: |
            **/cheeky-*.img.xz
            **/cheeky-*.tar.gz
            **/cheeky-*.zip
            **/cheeky-*.sha256
            **/cheeky-*.md5
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
