name: Build Cheeky Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0-dev'

permissions:
  contents: write

jobs:
  build-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Download and customize DietPi images
        run: |
          mkdir -p release-assets
          echo "Building Cheeky DietPi images..."

          # Install dependencies for image manipulation
          sudo apt-get update -qq
          sudo apt-get install -y -qq kpartx qemu-utils binfmt-support qemu-user-static > /dev/null 2>&1

          # Map architecture to DietPi image filename
          declare -A dietpi_images=(
            [armv6]="DietPi_RPi1-ARMv6-Bookworm"
            [armv7]="DietPi_RPi2-ARMv7-Bookworm"
            [armv8]="DietPi_RPi234-ARMv8-Bookworm"
          )

          for arch in armv6 armv7 armv8; do
            echo ""
            echo "=========================================="
            echo "Building $arch image..."
            echo "=========================================="

            IMG_FILE="/tmp/dietpi-${arch}.img"
            IMG_XZ="release-assets/cheeky-${arch}-${{ steps.version.outputs.VERSION }}.img.xz"
            DIETPI_IMG="${dietpi_images[$arch]}"

            # Download DietPi image from official source
            echo "Downloading DietPi $arch image: $DIETPI_IMG.img.xz"
            wget -q --show-progress \
              "https://dietpi.com/downloads/images/${DIETPI_IMG}.img.xz" \
              -O "/tmp/dietpi-${arch}.img.xz" || {
              echo "ERROR: Failed to download DietPi $arch image"
              exit 1
            }

            # Extract image for customization
            echo "Extracting image for customization..."
            xz -d "/tmp/dietpi-${arch}.img.xz"

            # Find partition offset using fdisk
            echo "Finding partition offset..."
            PARTITION_START=$(sudo fdisk -lu "$IMG_FILE" 2>/dev/null | grep "\.img2" | awk '{print $2}')
            if [ -z "$PARTITION_START" ]; then
              echo "ERROR: Could not find partition in image"
              exit 1
            fi
            OFFSET=$((PARTITION_START * 512))
            echo "Partition starts at sector $PARTITION_START (offset: $OFFSET bytes)"

            # Mount with calculated offset
            echo "Mounting filesystem..."
            sudo mkdir -p /mnt/cheeky-${arch}
            sudo mount -o loop,offset=$OFFSET "$IMG_FILE" /mnt/cheeky-${arch}

            if mountpoint -q /mnt/cheeky-${arch}; then
              echo "Installing Cheeky components..."

              # Copy configuration files
              sudo cp -r config/bluetooth-web-manager /mnt/cheeky-${arch}/root/ 2>/dev/null || true
              sudo cp -r config/mopidy.conf /mnt/cheeky-${arch}/root/ 2>/dev/null || true
              sudo cp -r config/Automation_Custom_Script.sh /mnt/cheeky-${arch}/root/ 2>/dev/null || true

              # Copy documentation
              sudo cp -r docs /mnt/cheeky-${arch}/root/cheeky-docs 2>/dev/null || true

              # Create version marker
              sudo touch /mnt/cheeky-${arch}/root/.cheeky-${{ steps.version.outputs.VERSION }}

              echo "Customization complete"
              sudo umount /mnt/cheeky-${arch}
            else
              echo "WARNING: Could not mount filesystem, skipping customization"
            fi

            sudo rmdir /mnt/cheeky-${arch} 2>/dev/null || true

            # Compress customized image
            echo "Compressing customized image..."
            xz -9v "$IMG_FILE"
            mv "$IMG_FILE.xz" "$IMG_XZ"

            # Checksum
            sha256sum "$IMG_XZ" > "${IMG_XZ}.sha256"

            echo "✓ $arch image complete ($(du -h $IMG_XZ | cut -f1))"
          done

          echo ""
          echo "=========================================="
          echo "Images ready!"
          echo "=========================================="
          ls -lah release-assets/

      - name: Build QEMU Ubuntu image
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          echo "Building QEMU-optimized Ubuntu image..."

          # Download Ubuntu 24.04 LTS cloud image for ARM64 (optimized for QEMU)
          echo "Downloading Ubuntu cloud image..."
          wget -q --show-progress \
            "https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-arm64.img" \
            -O /tmp/ubuntu-qemu.img || {
            echo "ERROR: Failed to download Ubuntu image"
            exit 1
          }

          # Resize image to 10GB
          echo "Resizing image to 10GB..."
          qemu-img resize /tmp/ubuntu-qemu.img 10G

          # Mount and customize
          echo "Mounting and customizing..."
          LOOP_DEV=$(sudo losetup -f)
          sudo losetup "$LOOP_DEV" /tmp/ubuntu-qemu.img
          sudo partprobe "$LOOP_DEV"

          sudo mkdir -p /mnt/cheeky-qemu
          sudo mount "${LOOP_DEV}p1" /mnt/cheeky-qemu

          if mountpoint -q /mnt/cheeky-qemu; then
            echo "Installing Cheeky components..."
            sudo mkdir -p /mnt/cheeky-qemu/root/cheeky
            sudo cp -r config /mnt/cheeky-qemu/root/cheeky/ 2>/dev/null || true
            sudo cp -r docs /mnt/cheeky-qemu/root/cheeky/ 2>/dev/null || true
            sudo touch /mnt/cheeky-qemu/root/.cheeky-$VERSION
            sudo umount /mnt/cheeky-qemu
          fi

          sudo losetup -d "$LOOP_DEV"
          sudo rmdir /mnt/cheeky-qemu 2>/dev/null || true

          # Compress
          echo "Compressing image..."
          qemu-img convert -c -O qcow2 /tmp/ubuntu-qemu.img "release-assets/cheeky-qemu-ubuntu-${VERSION}.qcow2"
          sha256sum "release-assets/cheeky-qemu-ubuntu-${VERSION}.qcow2" > "release-assets/cheeky-qemu-ubuntu-${VERSION}.qcow2.sha256"

          echo "QEMU image ready"
          ls -lah release-assets/cheeky-qemu*

      - name: Create QEMU launcher bundles
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          REPO="${{ github.repository }}"
          mkdir -p qemu-build/{linux,macos,windows}

          # Copy and process QEMU scripts
          for dir in linux macos windows; do
            cp -r qemu/$dir/* qemu-build/$dir/

            # Rename templates
            [ -f "qemu-build/$dir/start-qemu.sh.template" ] && mv "qemu-build/$dir/start-qemu.sh.template" "qemu-build/$dir/start-qemu.sh"
            [ -f "qemu-build/$dir/start-qemu.bat.template" ] && mv "qemu-build/$dir/start-qemu.bat.template" "qemu-build/$dir/start-qemu.bat"

            # Replace placeholders
            for file in qemu-build/$dir/*; do
              if [ -f "$file" ]; then
                sed -i "s|VERSION_PLACEHOLDER|$VERSION|g" "$file"
                sed -i "s|REPO_PLACEHOLDER|$REPO|g" "$file"
              fi
            done
          done

          # Create README for QEMU bundles
          echo "Creating QEMU README..."
          for dir in qemu-build/{linux,macos,windows}; do
            echo "CHEEKY QEMU BUNDLE" > "$dir/README.txt"
            echo "==================" >> "$dir/README.txt"
            echo "" >> "$dir/README.txt"
            echo "This bundle runs Cheeky in QEMU using Ubuntu cloud image." >> "$dir/README.txt"
            echo "" >> "$dir/README.txt"
            echo "Usage:" >> "$dir/README.txt"
            echo "1. Download cheeky-qemu-ubuntu-*.qcow2 from releases" >> "$dir/README.txt"
            echo "2. Place it in this directory" >> "$dir/README.txt"
            echo "3. Run launcher: ./start-qemu.sh or start-qemu.bat" >> "$dir/README.txt"
            echo "" >> "$dir/README.txt"
            echo "Access after boot (~1-2 minutes):" >> "$dir/README.txt"
            echo "- Radio: http://localhost:6680" >> "$dir/README.txt"
            echo "- Bluetooth: http://localhost:8080" >> "$dir/README.txt"
            echo "- SSH: ssh -p 2222 ubuntu@localhost (password: ubuntu)" >> "$dir/README.txt"
          done

          # Package bundles
          cd qemu-build
          tar czf ../release-assets/cheeky-qemu-linux-${VERSION}.tar.gz -C linux .
          tar czf ../release-assets/cheeky-qemu-macos-${VERSION}.tar.gz -C macos .
          cd windows && zip -r ../../release-assets/cheeky-qemu-windows-${VERSION}.zip . && cd ..

      - name: List release assets
        run: ls -lah release-assets/

      - name: Delete old release
        if: startsWith(github.ref, 'refs/tags/')
        run: gh release delete "${{ github.ref_name }}" -y 2>/dev/null || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Cheeky ${{ github.ref_name }}
          body: |
            ## Cheeky ${{ github.ref_name }}

            Download, flash, boot - that's it!

            ### For Physical Raspberry Pi

            | Pi Model | Download |
            |----------|----------|
            | Pi Zero 2 W, Pi 3, Pi 4, Pi 5 | cheeky-armv8-*.img.xz |
            | Pi 2 | cheeky-armv7-*.img.xz |
            | Pi Zero W, Pi 1 | cheeky-armv6-*.img.xz |

            ### Test in QEMU (No Pi Needed)

            | Platform | Download |
            |----------|----------|
            | Linux | cheeky-qemu-linux-*.tar.gz |
            | macOS | cheeky-qemu-macos-*.tar.gz |
            | Windows | cheeky-qemu-windows-*.zip |
          files: release-assets/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
