name: Build Cheeky Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0-dev'

permissions:
  contents: write

jobs:
  build-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Download Debian ARM64 cloud image
        run: |
          mkdir -p release-assets
          mkdir -p /tmp/cheeky-build
          cd /tmp/cheeky-build

          echo "Downloading Debian 12 Bookworm ARM64 cloud image..."
          wget -q --show-progress \
            "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-arm64.qcow2" \
            -O debian-12-arm64.qcow2 || {
            echo "ERROR: Failed to download Debian cloud image"
            exit 1
          }

          echo "Image downloaded"
          ls -lh debian-12-arm64.qcow2

      - name: Customize image for Cheeky
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          cd /tmp/cheeky-build

          # Install image manipulation tools
          sudo apt-get update -qq
          sudo apt-get install -y -qq qemu-utils > /dev/null 2>&1

          IMAGE_FILE="debian-12-arm64.qcow2"
          echo "Customizing Debian cloud image for Cheeky..."

          # Use qemu-nbd to mount Debian cloud image
          sudo modprobe nbd max_part=16
          sudo qemu-nbd -f qcow2 --connect=/dev/nbd0 "$IMAGE_FILE"
          sleep 2

          # Find partition (usually p1 on cloud images)
          PART_DEV="/dev/nbd0p1"
          if [ ! -b "$PART_DEV" ]; then
            echo "ERROR: Partition $PART_DEV not found"
            sudo qemu-nbd --disconnect /dev/nbd0
            exit 1
          fi

          echo "Mounting partition: $PART_DEV"
          sudo mkdir -p /mnt/cheeky-img
          sudo mount "$PART_DEV" /mnt/cheeky-img

          if mountpoint -q /mnt/cheeky-img; then
            echo "Installing Cheeky components..."

            # Prepare chroot environment
            sudo mount --bind /dev /mnt/cheeky-img/dev
            sudo mount --bind /proc /mnt/cheeky-img/proc
            sudo mount --bind /sys /mnt/cheeky-img/sys

            # Copy DNS for package installation
            sudo cp /etc/resolv.conf /mnt/cheeky-img/etc/resolv.conf

            # Copy Cheeky configuration files
            sudo mkdir -p /mnt/cheeky-img/root/cheeky
            sudo cp -r ${GITHUB_WORKSPACE}/config /mnt/cheeky-img/root/cheeky/
            sudo cp -r ${GITHUB_WORKSPACE}/docs /mnt/cheeky-img/root/cheeky/ 2>/dev/null || true

            # Create installation script
            cat > /tmp/cheeky-install.sh << 'CHROOT_EOF'
#!/bin/bash
set -e
export DEBIAN_FRONTEND=noninteractive

echo "[Cheeky] Updating package lists..."
apt-get update -qq

echo "[Cheeky] Installing core dependencies..."
apt-get install -y -qq \
  python3-pip \
  python3-dev \
  python3-glib \
  python3-dbus \
  build-essential \
  pulseaudio \
  pulseaudio-utils \
  bluez \
  bluez-tools \
  alsa-utils \
  avahi-daemon \
  wget \
  curl \
  git

echo "[Cheeky] Installing Python packages..."
pip3 install --break-system-packages \
  mopidy \
  mopidy-iris \
  mopidy-tunein \
  fastapi==0.109.0 \
  uvicorn[standard]==0.27.0 \
  pydantic==2.5.0 \
  python-multipart==0.0.6

echo "[Cheeky] Creating Mopidy configuration..."
mkdir -p /etc/mopidy
cp /root/cheeky/config/mopidy.conf /etc/mopidy/mopidy.conf

# Create Mopidy system user
useradd -r -m -s /bin/false -d /var/lib/mopidy mopidy 2>/dev/null || true
mkdir -p /var/lib/mopidy/media
chown -R mopidy:mopidy /var/lib/mopidy

echo "[Cheeky] Creating Mopidy systemd service..."
cat > /etc/systemd/system/mopidy.service << 'EOF'
[Unit]
Description=Mopidy Music Server
After=network.target sound.target

[Service]
Type=simple
User=mopidy
ExecStart=/usr/local/bin/mopidy --config /etc/mopidy/mopidy.conf
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

echo "[Cheeky] Installing Bluetooth Manager..."
mkdir -p /opt/cheeky/bluetooth-web-manager
cp -r /root/cheeky/config/bluetooth-web-manager/* /opt/cheeky/bluetooth-web-manager/

cat > /etc/systemd/system/cheeky-bluetooth-manager.service << 'EOF'
[Unit]
Description=Cheeky Bluetooth Manager
After=network.target bluetooth.service

[Service]
Type=simple
User=root
WorkingDirectory=/opt/cheeky/bluetooth-web-manager
ExecStart=/usr/bin/python3 -m uvicorn main:app --host 0.0.0.0 --port 8080
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

echo "[Cheeky] Installing Bluetooth auto-reconnect..."
cp /root/cheeky/config/bluetooth-reconnect.sh /usr/local/bin/cheeky-bluetooth-reconnect.sh
chmod +x /usr/local/bin/cheeky-bluetooth-reconnect.sh

cat > /etc/systemd/system/cheeky-bluetooth-reconnect.service << 'EOF'
[Unit]
Description=Cheeky Bluetooth Auto-Reconnect
After=bluetooth.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/cheeky-bluetooth-reconnect.sh
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

echo "[Cheeky] Enabling services..."
systemctl daemon-reload
systemctl enable mopidy
systemctl enable cheeky-bluetooth-manager
systemctl enable cheeky-bluetooth-reconnect
systemctl enable bluetooth
systemctl enable avahi-daemon

echo "[Cheeky] Creating version marker..."
echo "CHEEKY_VERSION=VERSION_PLACEHOLDER" > /etc/cheeky-version
touch /root/.cheeky-installed

echo "[Cheeky] Installation complete!"
CHROOT_EOF

            # Replace VERSION placeholder
            sed -i "s|VERSION_PLACEHOLDER|$VERSION|g" /tmp/cheeky-install.sh

            # Copy script into image and execute in chroot
            sudo cp /tmp/cheeky-install.sh /mnt/cheeky-img/tmp/cheeky-install.sh
            sudo chmod +x /mnt/cheeky-img/tmp/cheeky-install.sh
            sudo chroot /mnt/cheeky-img /tmp/cheeky-install.sh

            # Cleanup chroot mounts
            sudo umount /mnt/cheeky-img/sys
            sudo umount /mnt/cheeky-img/proc
            sudo umount /mnt/cheeky-img/dev

            echo "Cheeky customization complete"
            sudo umount /mnt/cheeky-img
          else
            echo "ERROR: Could not mount filesystem"
            sudo qemu-nbd --disconnect /dev/nbd0
            exit 1
          fi

          # Cleanup
          sudo rmdir /mnt/cheeky-img 2>/dev/null || true
          sudo qemu-nbd --disconnect /dev/nbd0

          echo "Image customization complete"
          ls -lh "$IMAGE_FILE"

      - name: Extract kernel and initrd for QEMU direct boot
        run: |
          cd /tmp/cheeky-build

          echo "Extracting kernel and initrd from Debian cloud image..."

          # Re-mount image to extract kernel/initrd
          sudo qemu-nbd -f qcow2 --connect=/dev/nbd0 debian-12-arm64.qcow2
          sleep 2
          sudo mkdir -p /mnt/cheeky-img
          sudo mount /dev/nbd0p1 /mnt/cheeky-img

          # Copy kernel and initrd
          sudo cp /mnt/cheeky-img/boot/vmlinuz-* vmlinuz
          sudo cp /mnt/cheeky-img/boot/initrd.img-* initrd.img
          sudo chown $(whoami):$(whoami) vmlinuz initrd.img

          # Get the UUID of the root filesystem for robust device identification
          ROOT_UUID=$(sudo blkid -s UUID -o value /dev/nbd0p1)
          echo "Root filesystem UUID: $ROOT_UUID"
          echo "$ROOT_UUID" > root-uuid.txt

          echo "Extracted files:"
          ls -lh vmlinuz initrd.img root-uuid.txt

          # Cleanup
          sudo umount /mnt/cheeky-img
          sudo qemu-nbd --disconnect /dev/nbd0
          sudo rmdir /mnt/cheeky-img 2>/dev/null || true

      - name: Create QEMU qcow2 image
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          cd /tmp/cheeky-build

          IMAGE_FILE="debian-12-arm64.qcow2"
          echo "Compressing Debian cloud image for QEMU..."
          qemu-img convert -c -O qcow2 "$IMAGE_FILE" cheeky-qemu-debian-${VERSION}.qcow2

          echo "Compressed image size:"
          ls -lh cheeky-qemu-debian-${VERSION}.qcow2

          sha256sum cheeky-qemu-debian-${VERSION}.qcow2 > cheeky-qemu-debian-${VERSION}.qcow2.sha256

          # Move to release assets
          cp cheeky-qemu-debian-${VERSION}.qcow2* ${GITHUB_WORKSPACE}/release-assets/

          echo "QEMU image ready"
          ls -lh ${GITHUB_WORKSPACE}/release-assets/cheeky-qemu-debian-${VERSION}.qcow2*

      - name: Create physical Pi img.xz image
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          cd /tmp/cheeky-build

          echo "Converting qcow2 to raw image for physical Pi..."
          qemu-img convert -O raw debian-12-arm64.qcow2 cheeky-debian-${VERSION}.img

          echo "Compressing image for Pi..."
          xz -9v cheeky-debian-${VERSION}.img

          # Move to release assets
          cp cheeky-debian-${VERSION}.img.xz ${GITHUB_WORKSPACE}/release-assets/
          sha256sum ${GITHUB_WORKSPACE}/release-assets/cheeky-debian-${VERSION}.img.xz > ${GITHUB_WORKSPACE}/release-assets/cheeky-debian-${VERSION}.img.xz.sha256

          echo "Pi image ready"
          ls -lh ${GITHUB_WORKSPACE}/release-assets/cheeky-debian-${VERSION}.img.xz*

      - name: Create cloud-init seed for QEMU
        run: |
          cd /tmp/cheeky-build

          # Create cloud-init user-data
          cat > user-data << 'EOF'
          #cloud-config
          users:
            - name: debian
              gecos: Debian User
              sudo: ALL=(ALL) NOPASSWD:ALL
              groups: users, admin, sudo
              shell: /bin/bash
              lock_passwd: false
              # Password: cheeky
              passwd: $6$dDWS5sFZ23QQ8WnP$TtDseO5yvETqIHfKEDfIfb4DoN1Z2Bk4WP1uCXZfhwSDTSkMNyTWM/qqqiQcrScUE/ksfA0FtMtm8bHqUO7ex.

          ssh_pwauth: true
          package_update: false
          package_upgrade: false

          runcmd:
            - systemctl restart ssh
          EOF

          # Create meta-data
          cat > meta-data << 'EOF'
          instance-id: cheeky-qemu-001
          local-hostname: cheeky
          EOF

          # Create NoCloud ISO seed
          sudo apt-get install -y -qq genisoimage > /dev/null 2>&1
          genisoimage -output seed.iso -volid cidata -joliet -rock user-data meta-data

          echo "Cloud-init seed created:"
          ls -lh seed.iso

      - name: Create QEMU launcher bundles
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          REPO="${{ github.repository }}"
          mkdir -p qemu-build/{linux,macos,windows}

          # Copy kernel, initrd, cloud-init seed, and UUID to build directory
          cd /tmp/cheeky-build
          cp vmlinuz ${GITHUB_WORKSPACE}/qemu-build/linux/
          cp initrd.img ${GITHUB_WORKSPACE}/qemu-build/linux/
          cp seed.iso ${GITHUB_WORKSPACE}/qemu-build/linux/
          cp root-uuid.txt ${GITHUB_WORKSPACE}/qemu-build/linux/
          cp vmlinuz ${GITHUB_WORKSPACE}/qemu-build/macos/
          cp initrd.img ${GITHUB_WORKSPACE}/qemu-build/macos/
          cp seed.iso ${GITHUB_WORKSPACE}/qemu-build/macos/
          cp root-uuid.txt ${GITHUB_WORKSPACE}/qemu-build/macos/
          cp vmlinuz ${GITHUB_WORKSPACE}/qemu-build/windows/
          cp initrd.img ${GITHUB_WORKSPACE}/qemu-build/windows/
          cp seed.iso ${GITHUB_WORKSPACE}/qemu-build/windows/
          cp root-uuid.txt ${GITHUB_WORKSPACE}/qemu-build/windows/

          cd ${GITHUB_WORKSPACE}

          # Copy and process QEMU scripts
          for dir in linux macos windows; do
            cp -r qemu/$dir/* qemu-build/$dir/

            # Rename templates
            [ -f "qemu-build/$dir/start-qemu.sh.template" ] && mv "qemu-build/$dir/start-qemu.sh.template" "qemu-build/$dir/start-qemu.sh"
            [ -f "qemu-build/$dir/start-qemu.bat.template" ] && mv "qemu-build/$dir/start-qemu.bat.template" "qemu-build/$dir/start-qemu.bat"

            # Replace placeholders
            for file in qemu-build/$dir/*; do
              if [ -f "$file" ]; then
                sed -i "s|VERSION_PLACEHOLDER|$VERSION|g" "$file"
                sed -i "s|REPO_PLACEHOLDER|$REPO|g" "$file"
              fi
            done
          done

          # Create README for QEMU bundles
          echo "Creating QEMU README..."
          for dir in qemu-build/{linux,macos,windows}; do
            echo "CHEEKY QEMU BUNDLE" > "$dir/README.txt"
            echo "==================" >> "$dir/README.txt"
            echo "" >> "$dir/README.txt"
            echo "This bundle runs Cheeky in QEMU using Debian 12 Bookworm." >> "$dir/README.txt"
            echo "" >> "$dir/README.txt"
            echo "Usage:" >> "$dir/README.txt"
            echo "1. Download cheeky-qemu-debian-*.qcow2 from releases" >> "$dir/README.txt"
            echo "2. Place it in this directory" >> "$dir/README.txt"
            echo "3. Run launcher: ./start-qemu.sh or start-qemu.bat" >> "$dir/README.txt"
            echo "" >> "$dir/README.txt"
            echo "Access after boot (~1-2 minutes):" >> "$dir/README.txt"
            echo "- Radio: http://localhost:6680" >> "$dir/README.txt"
            echo "- Bluetooth: http://localhost:8080" >> "$dir/README.txt"
            echo "- SSH: ssh -p 2222 debian@localhost (password set on first boot)" >> "$dir/README.txt"
          done

          # Package bundles
          cd qemu-build
          tar czf ../release-assets/cheeky-qemu-linux-${VERSION}.tar.gz -C linux .
          tar czf ../release-assets/cheeky-qemu-macos-${VERSION}.tar.gz -C macos .
          cd windows && zip -r ../../release-assets/cheeky-qemu-windows-${VERSION}.zip . && cd ..

      - name: List release assets
        run: ls -lah release-assets/

      - name: Delete old release
        if: startsWith(github.ref, 'refs/tags/')
        run: gh release delete "${{ github.ref_name }}" -y 2>/dev/null || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Cheeky ${{ github.ref_name }}
          body: |
            ## Cheeky ${{ github.ref_name }}

            Lightweight Debian-based internet radio system. Download, flash, boot - that's it!

            ### For Physical Raspberry Pi

            **Compatible with:** All Raspberry Pi ARM64 models (Pi Zero 2 W, 3, 4, 5)

            Download: `cheeky-debian-${{ github.ref_name }}.img.xz`

            Flash with Raspberry Pi Imager, Balena Etcher, or `dd`:
            ```bash
            unxz cheeky-debian-v1.0.0.img.xz
            sudo dd if=cheeky-debian-v1.0.0.img of=/dev/sdX bs=4M status=progress
            sync
            ```

            Default user: `debian` (password configured on first boot via cloud-init)

            ### Test in QEMU (No Pi Needed)

            **Choose your platform:**

            | Platform | Download |
            |----------|----------|
            | Linux | `cheeky-qemu-linux-*.tar.gz` |
            | macOS | `cheeky-qemu-macos-*.tar.gz` |
            | Windows | `cheeky-qemu-windows-*.zip` |

            **Quick start:**
            ```bash
            tar xzf cheeky-qemu-linux-v1.0.0.tar.gz
            cd linux
            ./start-qemu.sh
            # First run downloads ~800MB image, subsequent runs start immediately
            # Access: http://localhost:6680 (radio) http://localhost:8080 (Bluetooth)
            # SSH: ssh -p 2222 debian@localhost
            ```
          files: release-assets/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
