name: Build Cheeky Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0-dev'

permissions:
  contents: write

jobs:
  build-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Download Ubuntu 24.04 LTS cloud image
        run: |
          mkdir -p release-assets
          mkdir -p /tmp/cheeky-build
          cd /tmp/cheeky-build

          echo "Downloading Ubuntu 24.04 LTS ARM64 cloud image..."
          wget -q --show-progress \
            "https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-arm64.img" \
            -O ubuntu-24.04-arm64.img || {
            echo "ERROR: Failed to download Ubuntu image"
            exit 1
          }

          echo "Image downloaded successfully"
          ls -lh ubuntu-24.04-arm64.img

      - name: Customize Ubuntu image for Cheeky
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          cd /tmp/cheeky-build

          # Install image manipulation tools
          sudo apt-get update -qq
          sudo apt-get install -y -qq qemu-utils kpartx > /dev/null 2>&1

          echo "Customizing Ubuntu image for Cheeky..."

          # Resize image to 10GB
          qemu-img resize ubuntu-24.04-arm64.img 10G

          # Mount using kpartx (handles partitions automatically)
          LOOP_DEV=$(sudo losetup -f)
          sudo losetup "$LOOP_DEV" ubuntu-24.04-arm64.img
          sudo kpartx -av "$LOOP_DEV"

          # Get the partition name from kpartx
          PART_NAME=$(basename $(sudo kpartx -l "$LOOP_DEV" 2>/dev/null | grep -oP '/dev/mapper/\S+' | head -1))

          if [ -z "$PART_NAME" ]; then
            echo "ERROR: Could not identify partition from kpartx"
            sudo kpartx -dv "$LOOP_DEV"
            sudo losetup -d "$LOOP_DEV"
            exit 1
          fi

          echo "Mounting partition: /dev/mapper/$PART_NAME"
          sudo mkdir -p /mnt/cheeky-ubuntu
          sudo mount "/dev/mapper/$PART_NAME" /mnt/cheeky-ubuntu

          if mountpoint -q /mnt/cheeky-ubuntu; then
            echo "Installing Cheeky components..."

            # Copy configuration files
            sudo mkdir -p /mnt/cheeky-ubuntu/root/cheeky
            sudo cp -r ${GITHUB_WORKSPACE}/config /mnt/cheeky-ubuntu/root/cheeky/ 2>/dev/null || true
            sudo cp -r ${GITHUB_WORKSPACE}/docs /mnt/cheeky-ubuntu/root/cheeky/ 2>/dev/null || true
            sudo touch /mnt/cheeky-ubuntu/root/.cheeky-$VERSION

            echo "Customization complete"
            sudo umount /mnt/cheeky-ubuntu
          else
            echo "ERROR: Could not mount filesystem"
            sudo kpartx -dv "$LOOP_DEV"
            sudo losetup -d "$LOOP_DEV"
            exit 1
          fi

          # Cleanup
          sudo kpartx -dv "$LOOP_DEV"
          sudo losetup -d "$LOOP_DEV"
          sudo rmdir /mnt/cheeky-ubuntu 2>/dev/null || true

          echo "Image customization complete"
          ls -lh ubuntu-24.04-arm64.img

      - name: Create QEMU qcow2 image
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          cd /tmp/cheeky-build

          echo "Converting to qcow2 format for QEMU..."
          qemu-img convert -c -O qcow2 ubuntu-24.04-arm64.img cheeky-qemu-ubuntu-${VERSION}.qcow2
          sha256sum cheeky-qemu-ubuntu-${VERSION}.qcow2 > cheeky-qemu-ubuntu-${VERSION}.qcow2.sha256

          # Move to release assets
          cp cheeky-qemu-ubuntu-${VERSION}.qcow2* ${GITHUB_WORKSPACE}/release-assets/

          echo "QEMU image ready"
          ls -lh cheeky-qemu-ubuntu-${VERSION}.qcow2*

      - name: Create physical Pi img.xz image
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          cd /tmp/cheeky-build

          echo "Converting to raw image for physical Pi..."
          # Just use the resized image as-is, compress with xz
          xz -9v ubuntu-24.04-arm64.img

          # Move to release assets
          cp ubuntu-24.04-arm64.img.xz ${GITHUB_WORKSPACE}/release-assets/cheeky-ubuntu-${VERSION}.img.xz
          sha256sum ${GITHUB_WORKSPACE}/release-assets/cheeky-ubuntu-${VERSION}.img.xz > ${GITHUB_WORKSPACE}/release-assets/cheeky-ubuntu-${VERSION}.img.xz.sha256

          echo "Pi image ready"
          ls -lh ${GITHUB_WORKSPACE}/release-assets/cheeky-ubuntu-${VERSION}.img.xz*

      - name: Create QEMU launcher bundles
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          REPO="${{ github.repository }}"
          mkdir -p qemu-build/{linux,macos,windows}

          # Copy and process QEMU scripts
          for dir in linux macos windows; do
            cp -r qemu/$dir/* qemu-build/$dir/

            # Rename templates
            [ -f "qemu-build/$dir/start-qemu.sh.template" ] && mv "qemu-build/$dir/start-qemu.sh.template" "qemu-build/$dir/start-qemu.sh"
            [ -f "qemu-build/$dir/start-qemu.bat.template" ] && mv "qemu-build/$dir/start-qemu.bat.template" "qemu-build/$dir/start-qemu.bat"

            # Replace placeholders
            for file in qemu-build/$dir/*; do
              if [ -f "$file" ]; then
                sed -i "s|VERSION_PLACEHOLDER|$VERSION|g" "$file"
                sed -i "s|REPO_PLACEHOLDER|$REPO|g" "$file"
              fi
            done
          done

          # Create README for QEMU bundles
          echo "Creating QEMU README..."
          for dir in qemu-build/{linux,macos,windows}; do
            echo "CHEEKY QEMU BUNDLE" > "$dir/README.txt"
            echo "==================" >> "$dir/README.txt"
            echo "" >> "$dir/README.txt"
            echo "This bundle runs Cheeky in QEMU using Ubuntu cloud image." >> "$dir/README.txt"
            echo "" >> "$dir/README.txt"
            echo "Usage:" >> "$dir/README.txt"
            echo "1. Download cheeky-qemu-ubuntu-*.qcow2 from releases" >> "$dir/README.txt"
            echo "2. Place it in this directory" >> "$dir/README.txt"
            echo "3. Run launcher: ./start-qemu.sh or start-qemu.bat" >> "$dir/README.txt"
            echo "" >> "$dir/README.txt"
            echo "Access after boot (~1-2 minutes):" >> "$dir/README.txt"
            echo "- Radio: http://localhost:6680" >> "$dir/README.txt"
            echo "- Bluetooth: http://localhost:8080" >> "$dir/README.txt"
            echo "- SSH: ssh -p 2222 ubuntu@localhost (password: ubuntu)" >> "$dir/README.txt"
          done

          # Package bundles
          cd qemu-build
          tar czf ../release-assets/cheeky-qemu-linux-${VERSION}.tar.gz -C linux .
          tar czf ../release-assets/cheeky-qemu-macos-${VERSION}.tar.gz -C macos .
          cd windows && zip -r ../../release-assets/cheeky-qemu-windows-${VERSION}.zip . && cd ..

      - name: List release assets
        run: ls -lah release-assets/

      - name: Delete old release
        if: startsWith(github.ref, 'refs/tags/')
        run: gh release delete "${{ github.ref_name }}" -y 2>/dev/null || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Cheeky ${{ github.ref_name }}
          body: |
            ## Cheeky ${{ github.ref_name }}

            Ubuntu-based internet radio for Raspberry Pi. Download, flash, boot - that's it!

            ### For Physical Raspberry Pi

            **Compatible with:** Pi Zero 2 W, Pi 3, Pi 4, Pi 5, Pi 2, Pi Zero W, Pi 1

            Download: `cheeky-ubuntu-${{ github.ref_name }}.img.xz`

            Flash with Raspberry Pi Imager, Balena Etcher, or `dd`:
            ```bash
            unxz cheeky-ubuntu-v1.0.0.img.xz
            sudo dd if=cheeky-ubuntu-v1.0.0.img of=/dev/sdX bs=4M status=progress
            ```

            ### Test in QEMU (No Pi Needed)

            **Choose your platform:**

            | Platform | Download |
            |----------|----------|
            | Linux | `cheeky-qemu-linux-*.tar.gz` |
            | macOS | `cheeky-qemu-macos-*.tar.gz` |
            | Windows | `cheeky-qemu-windows-*.zip` |

            **Quick start:**
            ```bash
            tar xzf cheeky-qemu-linux-v1.0.0.tar.gz
            cd linux
            ./start-qemu.sh
            # Access: http://localhost:6680 (radio) http://localhost:8080 (Bluetooth)
            ```
          files: release-assets/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
